### ISSUE TITLE
Test cases failure due to 'document_id' to 'document' mismatch.

### ISSUE THREAD

**Issue by rakeshgunduka** [coleifer/scout#5]
Screen Shot attached.
![Error](https://user-images.githubusercontent.com/6688066/35692623-df37e94e-07a1-11e8-8f33-25cf6f80e9de.png)

**Comment by coleifer** [comment]
Thanks, I've pushed a fix. 201f2e28467ffa0ca0320001f1666df46810273a

As an aside, I love the light-cyan color of your terminal text.

**Comment by coleifer** [comment]
I'm creating a travis.yml and will set up continuous-integration for the project.

**Comment by rakeshgunduka** [comment]
+1 That would be great.

**Comment by coleifer** [comment]
https://travis-ci.org/coleifer/scout
