### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by monikatrivedi** [coleifer/scout#7]
I am trying to run this command on python v3:
   client.create_index('test')                                                                                                                                                               
and I got this error
   TypeError: the JSON object must be str, not 'bytes'

Even if I try to use client.get_index('sample') it gives me same error.
Can you help me out with this.

**Comment by coleifer** [comment]
Are you using python 2 for the server process? Which python 3? You might want to bump up to 3.6 if you're on something older.

**Comment by coleifer** [comment]
Can you share the full traceback, and not just the error? Where exactly in the scout client code is this occurring?

**Comment by monikatrivedi** [comment]
>>> from scout_client import Scout
>>> client = Scout('http://localhost:8000/')
>>> client.create_index('set')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scout-3.0.2/scout_client.py", line 128, in create_index
    return self.post('/', {'name': name})
  File "/scout-3.0.2/scout_client.py", line 55, in post
    return self.post_json(url, data)
  File "/scout-3.0.2/scout_client.py", line 65, in post_json
    return json.loads(urlopen(request).read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

I am working on python version 3.5.2.
