### ISSUE TITLE
 Manage 2 profiles: 1 public (read only) and 1 admin (write permission)

### ISSUE THREAD

**Issue by Krazybug** [coleifer/scout#8]
Hello, 

Scout allows you to use a global key to get a full access to the API (GET, POST, ...).

It would have been nice to allow public access without requiring the key for read access (GET endpoints) when an key access is configured, eventually with a quota per IP address. 

Other solutions: provide a way to generate readonly token for a more robust solution or provide [basic auth](https://blog.miguelgrinberg.com/post/restful-authentication-with-flask) mecanism 

Best regards and thanks for this useful and simple project !

**Comment by coleifer** [comment]
Scout is not designed to be placed on the public internet. The API key is there if you *have* to, similar to how Redis supports an auth passphrase if you absolutely have to put it on the internet.

Scout has very simple client libraries. If you want to build an application with scout, just write a frontend wrapper that handles all that. You would probably want to sanitize the input, right?

**Comment by Krazybug** [comment]
Ok, thanks for your answer.

I just wanted to provide an API without any frontend. By _wrapper_ you mean redirect for other languages than python ? Otherwise I don't exactly see the value of a REST API.

**Comment by coleifer** [comment]
Would you expose an ElasticSearch server on the public internet? Would you expose your Redis server on the public internet?

**Comment by Krazybug** [comment]
Why not ? There are many pure REST services on the internet.
Thanks for your hard work whatever.
